flowchart LR
    %% Styles
    classDef actorStyle fill:#f9f,stroke:#333,stroke-width:2px;
    classDef ucStyle fill:#bbf,stroke:#333,stroke-width:2px,rx:20,ry:20;

    %% Acteurs
    Visiteur((Visiteur)):::actorStyle
    Etudiant((Etudiant)):::actorStyle
    Alumni((Alumni)):::actorStyle
    Entreprise((Entreprise)):::actorStyle
    Admin((Administrateur)):::actorStyle

    %% Cas d'utilisation
    subgraph "Système ESPRIT Connect"
        UC1([S'inscrire sur la plateforme]):::ucStyle
        UC2([S'authentifier / Connexion]):::ucStyle
        UC3([Gérer son profil public]):::ucStyle
        UC4([Consulter les offres]):::ucStyle
        UC5([Postuler à une offre]):::ucStyle
        UC6([Publier et Gérer des offres]):::ucStyle
        UC7([Participer au Forum]):::ucStyle
        UC8([Gérer le Mentorat]):::ucStyle
        UC9([Modérer le contenu]):::ucStyle
        UC10([Gérer les Utilisateurs & Validation]):::ucStyle
        UC11([Consulter les événements]):::ucStyle
    end

    %% Relations Visiteur
    Visiteur --> UC1
    Visiteur --> UC2
    Visiteur --> UC4

    %% Relations Etudiant
    Etudiant --> UC2
    Etudiant --> UC3
    Etudiant --> UC4
    Etudiant --> UC5
    Etudiant --> UC7
    Etudiant --> UC11
    Etudiant --> UC8

    %% Relations Alumni
    Alumni --> UC2
    Alumni --> UC3
    Alumni --> UC4
    Alumni --> UC5
    Alumni --> UC7
    Alumni --> UC11
    Alumni --> UC8

    %% Relations Entreprise
    Entreprise --> UC2
    Entreprise --> UC3
    Entreprise --> UC6

    %% Relations Admin
    Admin --> UC2
    Admin --> UC9
    Admin --> UC10
