spring.application.name=EspritConnect2
spring.datasource.url=jdbc:mysql://localhost:3306/EspritConnect2?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8088
server.servlet.context-path=/espritconnect

app.jwt.secret=EspritConnect2DevSecretKeyMustBe256BitsLongMinimumChars!!
app.jwt.expiration-ms=86400000
app.cors.allowed-origins=http://localhost:4200

### EMAIL / BREVO SMTP ###
spring.mail.host=
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

### APPLICATION EMAIL SETTINGS ###
app.mail.from=rahmaayari272@gmail.com
app.mail.from-name=EspritConnect
app.mail.admin-notification.subject=Nouvelle inscription en attente d'approbation
app.frontend.url=http://localhost:4200
